/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package track.it.gui;

import command.saveTool.SaveRecordToTextFile;
import model.BudgetList;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;

/**
 *
 * @author kungcheow
 */
public class GUISaveToTextFile extends javax.swing.JFrame {
    private String fileName;
    private BudgetList budgetList;
    /**
     * Creates new form Save
     */
    public GUISaveToTextFile(BudgetList budgetList) {
        initComponents();
        this.budgetList = budgetList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savePanel = new javax.swing.JPanel();
        fileNameInput = new javax.swing.JTextField();
        fileNameLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        requiredField = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCreateBtn = new javax.swing.JMenu();
        menuViewBgListBtn = new javax.swing.JMenu();
        menuLoadBtn = new javax.swing.JMenu();
        menuDownloadBtn = new javax.swing.JMenu();
        menuSaveBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save");

        savePanel.setBackground(new java.awt.Color(255, 255, 255));
        savePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));

        fileNameInput.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        fileNameLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        fileNameLabel.setForeground(new java.awt.Color(0, 51, 102));
        fileNameLabel.setText("Enter file name without extension");

        saveBtn.setBackground(new java.awt.Color(0, 153, 153));
        saveBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save to file");
        saveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        msgLabel.setBackground(new java.awt.Color(255, 255, 255));
        msgLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(0, 153, 153));
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        requiredField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        requiredField.setText("Required field");

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(savePanelLayout.createSequentialGroup()
                        .addComponent(requiredField)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(savePanelLayout.createSequentialGroup()
                        .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(savePanelLayout.createSequentialGroup()
                                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(fileNameInput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))))
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, savePanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(fileNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requiredField)
                .addGap(18, 18, 18)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));

        menuCreateBtn.setText("Create budget");
        menuCreateBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuCreateBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuCreateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCreateBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuCreateBtn);

        menuViewBgListBtn.setText("View budgets");
        menuViewBgListBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuViewBgListBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuViewBgListBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuViewBgListBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuViewBgListBtn);

        menuLoadBtn.setText("Load");
        menuLoadBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuLoadBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuLoadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLoadBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuLoadBtn);

        menuDownloadBtn.setText("Download");
        menuDownloadBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuDownloadBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuDownloadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDownloadBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuDownloadBtn);

        menuSaveBtn.setForeground(new java.awt.Color(0, 51, 102));
        menuSaveBtn.setText("Save");
        menuSaveBtn.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        menuBar.add(menuSaveBtn);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(579, 311));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if(fileNameInput.getText().trim().isEmpty()){
            msgLabel.setText("File name cannot be left blank.");
            msgLabel.setForeground(Color.red);
        }else{
            try {
                fileName = fileNameInput.getText() + ".csv";
                SaveRecordToTextFile saveRecordToTextFile = new SaveRecordToTextFile();
                saveRecordToTextFile.save(fileName,budgetList);

                msgLabel.setText("Your record is saved.");
                msgLabel.setForeground(Color.blue);
            } catch (FileNotFoundException fileNotFoundException) {
                fileNotFoundException.printStackTrace();
            } catch (UnsupportedEncodingException unicodeException) {
                unicodeException.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void menuCreateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCreateBtnMouseClicked
        this.dispose();
        GUICreateBudget createBudget = new GUICreateBudget(budgetList);
        createBudget.setVisible(true);
    }//GEN-LAST:event_menuCreateBtnMouseClicked

    private void menuViewBgListBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuViewBgListBtnMouseClicked
        this.dispose();
        GUIViewBudgetList viewBudgetList = new GUIViewBudgetList(budgetList);
        viewBudgetList.setVisible(true);
    }//GEN-LAST:event_menuViewBgListBtnMouseClicked

    private void menuLoadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLoadBtnMouseClicked
        this.dispose();
        GUILoadTextFile loadTextFile = new GUILoadTextFile(budgetList);
        loadTextFile.setVisible(true);
    }//GEN-LAST:event_menuLoadBtnMouseClicked

    private void menuDownloadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDownloadBtnMouseClicked
        this.dispose();
        GUIDownloadTextFile downloadTextFile = new GUIDownloadTextFile(budgetList);
        downloadTextFile.setVisible(true);
    }//GEN-LAST:event_menuDownloadBtnMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUISaveToTextFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUISaveToTextFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUISaveToTextFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUISaveToTextFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUISaveToTextFile(new BudgetList()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fileNameInput;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCreateBtn;
    private javax.swing.JMenu menuDownloadBtn;
    private javax.swing.JMenu menuLoadBtn;
    private javax.swing.JMenu menuSaveBtn;
    private javax.swing.JMenu menuViewBgListBtn;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel requiredField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel savePanel;
    // End of variables declaration//GEN-END:variables
}
