/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package track.it.gui;

import exception.ExpensePurposeHasCommaException;
import exception.TitleHasCommaException;
import model.BudgetList;
import model.Expense;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kungcheow
 */
public class GUIViewBudgetDetail extends javax.swing.JFrame {
    private BudgetList budgetList;
    private int budgetIndex;
    //private DefaultTableModel expTableModel;
    /**
     * Creates new form GUIViewBudgetDetail
     */
    public GUIViewBudgetDetail(BudgetList budgetList, int budgetIndex) {
        initComponents();
        this.budgetList = budgetList;
        this.budgetIndex = budgetIndex;
        bgTitleContent.setText(budgetList.getBudgetItem(budgetIndex).getTitle());
        bgAmtContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBudget()));
        totalExpContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getTotalExpense()));
        balanceContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBalance()));
        addDataToExpenseTable(expTable);
        addDataToExpenseTable(editExpTable);
    }

    private void addDataToExpenseTable(JTable jTable){
        DefaultTableModel expTableModel = (DefaultTableModel) jTable.getModel();
        Object rowData[] = new Object[2];
        for(int i = 0; i < budgetList.getBudgetItem(budgetIndex).getExpenseListSize();i++){
            rowData[0] = budgetList.getBudgetItem(budgetIndex).getExpenseItem(i).getExpensePurpose();
            rowData[1] = budgetList.getBudgetItem(budgetIndex).getExpenseItem(i).getExpenseAmount();
            expTableModel.addRow(rowData);
        }
    }

    private void displayResetData(){
        DefaultTableModel expTableModel = (DefaultTableModel) expTable.getModel();
        DefaultTableModel editExpTableModel = (DefaultTableModel) editExpTable.getModel();
        bgAmtContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBudget()));
        totalExpContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getTotalExpense()));
        balanceContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBalance()));
        expTableModel.setRowCount(0);
        editExpTableModel.setRowCount(0);
        editExpPurposeInput.setText("");
        editExpAmtInput.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editExpDialog = new javax.swing.JDialog();
        editExpPanel = new javax.swing.JPanel();
        editExpTablePanel = new javax.swing.JScrollPane();
        editExpTable = new javax.swing.JTable();
        editExpPurposeLabel = new javax.swing.JLabel();
        editExpAmtLabel = new javax.swing.JLabel();
        editExpPurposeInput = new javax.swing.JTextField();
        editExpAmtInput = new javax.swing.JTextField();
        editExpUpdateBtn = new javax.swing.JButton();
        editExpInsertBtn = new javax.swing.JButton();
        editExpRemoveBtn = new javax.swing.JButton();
        editExpClickRowMsg = new javax.swing.JLabel();
        editExpFinishBtn = new javax.swing.JButton();
        msgLabelEditExp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        editTitleDialog = new javax.swing.JDialog();
        updateTitlePanel = new javax.swing.JPanel();
        enterTitleLabel = new javax.swing.JLabel();
        newTitleInput = new javax.swing.JTextField();
        submitEditTitleBtn = new javax.swing.JButton();
        cancelEditTitleBtn = new javax.swing.JButton();
        msgLabelEditTitle = new javax.swing.JLabel();
        requiredField = new javax.swing.JLabel();
        editBudgetDialog = new javax.swing.JDialog();
        editBgAmtPanel = new javax.swing.JPanel();
        enterAmtLabel = new javax.swing.JLabel();
        newAmtInput = new javax.swing.JTextField();
        submitEditBgBtn = new javax.swing.JButton();
        cancelEditBgBtn = new javax.swing.JButton();
        msgLabelEditBg = new javax.swing.JLabel();
        requiredField1 = new javax.swing.JLabel();
        resetConfirmDialog = new javax.swing.JDialog();
        resetConfirmPanel = new javax.swing.JPanel();
        askResetConfirmation = new javax.swing.JLabel();
        warningMsgReset = new javax.swing.JLabel();
        confirmResetBtn = new javax.swing.JButton();
        cancelResetBtn = new javax.swing.JButton();
        msgLabelReset = new javax.swing.JLabel();
        removeExpDialog = new javax.swing.JDialog();
        removeExpConfirmPanel = new javax.swing.JPanel();
        warningMsgRemoveExp = new javax.swing.JLabel();
        confirmRemoveExpBtn = new javax.swing.JButton();
        cancelRemoveExpBtn = new javax.swing.JButton();
        msgLabelRemoveExp = new javax.swing.JLabel();
        removeExpConfirmation = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        bgTitleLabel = new javax.swing.JLabel();
        bgAmtLabel = new javax.swing.JLabel();
        editBgTitleBtn = new javax.swing.JButton();
        editBgAmtBtn = new javax.swing.JButton();
        bgTitleContent = new javax.swing.JLabel();
        bgAmtContent = new javax.swing.JLabel();
        expTablePanel = new javax.swing.JScrollPane();
        expTable = new javax.swing.JTable();
        expLabel = new javax.swing.JLabel();
        totalExpLabel = new javax.swing.JLabel();
        editExpBtn = new javax.swing.JButton();
        totalExpContent = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();
        balanceContent = new javax.swing.JLabel();
        amtCAD = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        separatorLine = new javax.swing.JSeparator();
        resetBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuCreateBtn = new javax.swing.JMenu();
        menuViewBgListBtn = new javax.swing.JMenu();
        menuLoadBtn = new javax.swing.JMenu();
        menuDownloadBtn = new javax.swing.JMenu();
        menuSaveBtn = new javax.swing.JMenu();

        editExpPanel.setBackground(new java.awt.Color(255, 255, 255));
        editExpPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));

        editExpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purpose", "Amount"
            }
        ));
        editExpTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editExpTableMouseClicked(evt);
            }
        });
        editExpTablePanel.setViewportView(editExpTable);

        editExpPurposeLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        editExpPurposeLabel.setForeground(new java.awt.Color(0, 51, 102));
        editExpPurposeLabel.setText("Purpose (comma is not allowed)");

        editExpAmtLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        editExpAmtLabel.setForeground(new java.awt.Color(0, 51, 102));
        editExpAmtLabel.setText("Amount");

        editExpPurposeInput.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        editExpAmtInput.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        editExpUpdateBtn.setBackground(new java.awt.Color(0, 153, 153));
        editExpUpdateBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editExpUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        editExpUpdateBtn.setText("Update");
        editExpUpdateBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editExpUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpUpdateBtnActionPerformed(evt);
            }
        });

        editExpInsertBtn.setBackground(new java.awt.Color(0, 51, 102));
        editExpInsertBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editExpInsertBtn.setForeground(new java.awt.Color(255, 255, 255));
        editExpInsertBtn.setText("Insert");
        editExpInsertBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editExpInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpInsertBtnActionPerformed(evt);
            }
        });

        editExpRemoveBtn.setBackground(new java.awt.Color(0, 153, 153));
        editExpRemoveBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editExpRemoveBtn.setForeground(new java.awt.Color(255, 255, 255));
        editExpRemoveBtn.setText("Remove");
        editExpRemoveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editExpRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpRemoveBtnActionPerformed(evt);
            }
        });

        editExpClickRowMsg.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        editExpClickRowMsg.setText("Click row to select expense");

        editExpFinishBtn.setBackground(new java.awt.Color(102, 102, 102));
        editExpFinishBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editExpFinishBtn.setForeground(new java.awt.Color(255, 255, 255));
        editExpFinishBtn.setText("Finish editing");
        editExpFinishBtn.setToolTipText("");
        editExpFinishBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editExpFinishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpFinishBtnActionPerformed(evt);
            }
        });

        msgLabelEditExp.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        msgLabelEditExp.setForeground(new java.awt.Color(0, 153, 153));
        msgLabelEditExp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout editExpPanelLayout = new javax.swing.GroupLayout(editExpPanel);
        editExpPanel.setLayout(editExpPanelLayout);
        editExpPanelLayout.setHorizontalGroup(
            editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExpPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msgLabelEditExp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editExpTablePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(editExpPanelLayout.createSequentialGroup()
                        .addGroup(editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editExpPurposeLabel)
                            .addComponent(editExpPurposeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editExpAmtLabel)
                            .addComponent(editExpAmtInput)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editExpPanelLayout.createSequentialGroup()
                        .addComponent(editExpClickRowMsg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editExpPanelLayout.createSequentialGroup()
                        .addComponent(editExpUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editExpInsertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editExpRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editExpFinishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        editExpPanelLayout.setVerticalGroup(
            editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExpPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(editExpTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editExpClickRowMsg)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(editExpPurposeLabel)
                    .addComponent(editExpAmtLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editExpAmtInput, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(editExpPurposeInput))
                .addGap(26, 26, 26)
                .addGroup(editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editExpInsertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editExpUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editExpFinishBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editExpRemoveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(msgLabelEditExp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editExpDialogLayout = new javax.swing.GroupLayout(editExpDialog.getContentPane());
        editExpDialog.getContentPane().setLayout(editExpDialogLayout);
        editExpDialogLayout.setHorizontalGroup(
            editExpDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editExpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        editExpDialogLayout.setVerticalGroup(
            editExpDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExpDialogLayout.createSequentialGroup()
                .addComponent(editExpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        updateTitlePanel.setBackground(new java.awt.Color(255, 255, 255));
        updateTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));

        enterTitleLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        enterTitleLabel.setForeground(new java.awt.Color(0, 51, 102));
        enterTitleLabel.setText("Enter new title (without any comma)");

        newTitleInput.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        submitEditTitleBtn.setBackground(new java.awt.Color(0, 153, 153));
        submitEditTitleBtn.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        submitEditTitleBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitEditTitleBtn.setText("Submit");
        submitEditTitleBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        submitEditTitleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditTitleBtnActionPerformed(evt);
            }
        });

        cancelEditTitleBtn.setBackground(new java.awt.Color(0, 51, 102));
        cancelEditTitleBtn.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cancelEditTitleBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelEditTitleBtn.setText("Cancel");
        cancelEditTitleBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelEditTitleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditTitleBtnActionPerformed(evt);
            }
        });

        msgLabelEditTitle.setForeground(new java.awt.Color(0, 153, 153));
        msgLabelEditTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        requiredField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        requiredField.setText("Required field");

        javax.swing.GroupLayout updateTitlePanelLayout = new javax.swing.GroupLayout(updateTitlePanel);
        updateTitlePanel.setLayout(updateTitlePanelLayout);
        updateTitlePanelLayout.setHorizontalGroup(
            updateTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateTitlePanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(updateTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newTitleInput, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                        .addComponent(msgLabelEditTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(requiredField)
                    .addGroup(updateTitlePanelLayout.createSequentialGroup()
                        .addComponent(submitEditTitleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelEditTitleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enterTitleLabel))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        updateTitlePanelLayout.setVerticalGroup(
            updateTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateTitlePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(enterTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requiredField)
                .addGap(13, 13, 13)
                .addGroup(updateTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelEditTitleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitEditTitleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(msgLabelEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editTitleDialogLayout = new javax.swing.GroupLayout(editTitleDialog.getContentPane());
        editTitleDialog.getContentPane().setLayout(editTitleDialogLayout);
        editTitleDialogLayout.setHorizontalGroup(
            editTitleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTitleDialogLayout.createSequentialGroup()
                .addComponent(updateTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        editTitleDialogLayout.setVerticalGroup(
            editTitleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        editBgAmtPanel.setBackground(new java.awt.Color(255, 255, 255));
        editBgAmtPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));

        enterAmtLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        enterAmtLabel.setForeground(new java.awt.Color(0, 51, 102));
        enterAmtLabel.setText("Enter new budget amount");

        newAmtInput.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        submitEditBgBtn.setBackground(new java.awt.Color(0, 153, 153));
        submitEditBgBtn.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        submitEditBgBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitEditBgBtn.setText("Submit");
        submitEditBgBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        submitEditBgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditBgBtnActionPerformed(evt);
            }
        });

        cancelEditBgBtn.setBackground(new java.awt.Color(0, 51, 102));
        cancelEditBgBtn.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cancelEditBgBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelEditBgBtn.setText("Cancel");
        cancelEditBgBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelEditBgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditBgBtnActionPerformed(evt);
            }
        });

        msgLabelEditBg.setForeground(new java.awt.Color(0, 153, 153));
        msgLabelEditBg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        requiredField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        requiredField1.setText("Required field");

        javax.swing.GroupLayout editBgAmtPanelLayout = new javax.swing.GroupLayout(editBgAmtPanel);
        editBgAmtPanel.setLayout(editBgAmtPanelLayout);
        editBgAmtPanelLayout.setHorizontalGroup(
            editBgAmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editBgAmtPanelLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(editBgAmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(requiredField1)
                    .addGroup(editBgAmtPanelLayout.createSequentialGroup()
                        .addComponent(submitEditBgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelEditBgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enterAmtLabel)
                    .addComponent(newAmtInput, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(msgLabelEditBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );
        editBgAmtPanelLayout.setVerticalGroup(
            editBgAmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBgAmtPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(enterAmtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAmtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requiredField1)
                .addGap(8, 8, 8)
                .addGroup(editBgAmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitEditBgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelEditBgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(msgLabelEditBg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editBudgetDialogLayout = new javax.swing.GroupLayout(editBudgetDialog.getContentPane());
        editBudgetDialog.getContentPane().setLayout(editBudgetDialogLayout);
        editBudgetDialogLayout.setHorizontalGroup(
            editBudgetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editBgAmtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        editBudgetDialogLayout.setVerticalGroup(
            editBudgetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editBgAmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        resetConfirmPanel.setBackground(new java.awt.Color(255, 255, 255));
        resetConfirmPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));

        askResetConfirmation.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        askResetConfirmation.setForeground(new java.awt.Color(0, 51, 102));
        askResetConfirmation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        askResetConfirmation.setText("Do you really want to reset the budget?");

        warningMsgReset.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        warningMsgReset.setForeground(new java.awt.Color(204, 0, 51));
        warningMsgReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningMsgReset.setText("Warning: This action CANNOT be undone.");

        confirmResetBtn.setBackground(new java.awt.Color(0, 153, 153));
        confirmResetBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        confirmResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmResetBtn.setText("Yes");
        confirmResetBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirmResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmResetBtnActionPerformed(evt);
            }
        });

        cancelResetBtn.setBackground(new java.awt.Color(0, 51, 102));
        cancelResetBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cancelResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelResetBtn.setText("No");
        cancelResetBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResetBtnActionPerformed(evt);
            }
        });

        msgLabelReset.setForeground(new java.awt.Color(0, 0, 255));
        msgLabelReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout resetConfirmPanelLayout = new javax.swing.GroupLayout(resetConfirmPanel);
        resetConfirmPanel.setLayout(resetConfirmPanelLayout);
        resetConfirmPanelLayout.setHorizontalGroup(
            resetConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetConfirmPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(resetConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetConfirmPanelLayout.createSequentialGroup()
                        .addComponent(warningMsgReset)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resetConfirmPanelLayout.createSequentialGroup()
                            .addComponent(confirmResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cancelResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(msgLabelReset, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resetConfirmPanelLayout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(askResetConfirmation))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        resetConfirmPanelLayout.setVerticalGroup(
            resetConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(askResetConfirmation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningMsgReset)
                .addGap(18, 18, 18)
                .addGroup(resetConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(msgLabelReset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout resetConfirmDialogLayout = new javax.swing.GroupLayout(resetConfirmDialog.getContentPane());
        resetConfirmDialog.getContentPane().setLayout(resetConfirmDialogLayout);
        resetConfirmDialogLayout.setHorizontalGroup(
            resetConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resetConfirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        resetConfirmDialogLayout.setVerticalGroup(
            resetConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resetConfirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        removeExpDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        removeExpDialog.setBackground(new java.awt.Color(255, 255, 255));

        removeExpConfirmPanel.setBackground(new java.awt.Color(255, 255, 255));
        removeExpConfirmPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));

        warningMsgRemoveExp.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        warningMsgRemoveExp.setForeground(new java.awt.Color(204, 0, 51));
        warningMsgRemoveExp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningMsgRemoveExp.setText("Warning: This action CANNOT be undone.");

        confirmRemoveExpBtn.setBackground(new java.awt.Color(0, 153, 153));
        confirmRemoveExpBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        confirmRemoveExpBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmRemoveExpBtn.setText("Yes");
        confirmRemoveExpBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirmRemoveExpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRemoveExpBtnActionPerformed(evt);
            }
        });

        cancelRemoveExpBtn.setBackground(new java.awt.Color(0, 51, 102));
        cancelRemoveExpBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cancelRemoveExpBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelRemoveExpBtn.setText("No");
        cancelRemoveExpBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelRemoveExpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRemoveExpBtnActionPerformed(evt);
            }
        });

        msgLabelRemoveExp.setForeground(new java.awt.Color(0, 0, 255));
        msgLabelRemoveExp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        removeExpConfirmation.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        removeExpConfirmation.setForeground(new java.awt.Color(0, 51, 102));
        removeExpConfirmation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeExpConfirmation.setText("Do you really want to delete the budget?");

        javax.swing.GroupLayout removeExpConfirmPanelLayout = new javax.swing.GroupLayout(removeExpConfirmPanel);
        removeExpConfirmPanel.setLayout(removeExpConfirmPanelLayout);
        removeExpConfirmPanelLayout.setHorizontalGroup(
            removeExpConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeExpConfirmPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(removeExpConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeExpConfirmPanelLayout.createSequentialGroup()
                        .addComponent(warningMsgRemoveExp)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeExpConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, removeExpConfirmPanelLayout.createSequentialGroup()
                            .addComponent(confirmRemoveExpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cancelRemoveExpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(msgLabelRemoveExp, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(removeExpConfirmPanelLayout.createSequentialGroup()
                            .addComponent(removeExpConfirmation)
                            .addGap(12, 12, 12))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        removeExpConfirmPanelLayout.setVerticalGroup(
            removeExpConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeExpConfirmPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(removeExpConfirmation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningMsgRemoveExp)
                .addGap(18, 18, 18)
                .addGroup(removeExpConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmRemoveExpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelRemoveExpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(msgLabelRemoveExp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout removeExpDialogLayout = new javax.swing.GroupLayout(removeExpDialog.getContentPane());
        removeExpDialog.getContentPane().setLayout(removeExpDialogLayout);
        removeExpDialogLayout.setHorizontalGroup(
            removeExpDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeExpConfirmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        removeExpDialogLayout.setVerticalGroup(
            removeExpDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeExpConfirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget Detail");

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));

        bgTitleLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        bgTitleLabel.setForeground(new java.awt.Color(0, 51, 102));
        bgTitleLabel.setText("Budget title:");

        bgAmtLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        bgAmtLabel.setForeground(new java.awt.Color(0, 51, 102));
        bgAmtLabel.setText("Budget amount:");

        editBgTitleBtn.setBackground(new java.awt.Color(0, 153, 153));
        editBgTitleBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        editBgTitleBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBgTitleBtn.setText("Edit");
        editBgTitleBtn.setToolTipText("edit budget title");
        editBgTitleBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editBgTitleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBgTitleBtnActionPerformed(evt);
            }
        });

        editBgAmtBtn.setBackground(new java.awt.Color(0, 153, 153));
        editBgAmtBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        editBgAmtBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBgAmtBtn.setText("Edit");
        editBgAmtBtn.setToolTipText("edit budget amount");
        editBgAmtBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editBgAmtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBgAmtBtnActionPerformed(evt);
            }
        });

        bgTitleContent.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bgTitleContent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bgAmtContent.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bgAmtContent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        expTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purpose", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expTablePanel.setViewportView(expTable);

        expLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        expLabel.setForeground(new java.awt.Color(0, 51, 102));
        expLabel.setText("Expenses:");

        totalExpLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        totalExpLabel.setForeground(new java.awt.Color(0, 51, 102));
        totalExpLabel.setText("Total expense:");

        editExpBtn.setBackground(new java.awt.Color(0, 153, 153));
        editExpBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        editExpBtn.setForeground(new java.awt.Color(255, 255, 255));
        editExpBtn.setText("Add/Edit");
        editExpBtn.setToolTipText("edit expense information");
        editExpBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editExpBtn.setMaximumSize(new java.awt.Dimension(55, 22));
        editExpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpBtnActionPerformed(evt);
            }
        });

        totalExpContent.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        totalExpContent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        msgLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(51, 51, 255));
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        balanceContent.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        balanceContent.setForeground(new java.awt.Color(0, 153, 153));
        balanceContent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        amtCAD.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        amtCAD.setText("Amount in CAD");

        balanceLabel.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(0, 51, 102));
        balanceLabel.setText("Balance:");

        resetBtn.setBackground(new java.awt.Color(102, 102, 102));
        resetBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset amount");
        resetBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(amtCAD)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topPanelLayout.createSequentialGroup()
                        .addComponent(expLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editExpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topPanelLayout.createSequentialGroup()
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bgAmtLabel)
                            .addComponent(bgTitleLabel))
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(topPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(bgTitleContent, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(topPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bgAmtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBgTitleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editBgAmtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(totalExpLabel)
                        .addGap(27, 27, 27)
                        .addComponent(totalExpContent, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topPanelLayout.createSequentialGroup()
                        .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(balanceContent, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(expTablePanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorLine, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bgTitleContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bgTitleLabel))
                        .addGap(4, 4, 4))
                    .addComponent(editBgTitleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(topPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(bgAmtLabel))
                            .addComponent(bgAmtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editBgAmtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expLabel)
                    .addComponent(editExpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(expTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalExpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalExpContent, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amtCAD, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(separatorLine, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));

        menuCreateBtn.setText("Create budget");
        menuCreateBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuCreateBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuCreateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCreateBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuCreateBtn);

        menuViewBgListBtn.setText("View budgets");
        menuViewBgListBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuViewBgListBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuViewBgListBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuViewBgListBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuViewBgListBtn);

        menuLoadBtn.setText("Load");
        menuLoadBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuLoadBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuLoadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLoadBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuLoadBtn);

        menuDownloadBtn.setText("Download");
        menuDownloadBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuDownloadBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuDownloadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDownloadBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuDownloadBtn);

        menuSaveBtn.setText("Save");
        menuSaveBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuSaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSaveBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuSaveBtn);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(710, 842));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void editBgTitleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBgTitleBtnActionPerformed
        editTitleDialog.pack();
        editTitleDialog.setLocationRelativeTo(null);
        editTitleDialog.setSize(new Dimension(590, 330));
        editTitleDialog.setVisible(true);
    }//GEN-LAST:event_editBgTitleBtnActionPerformed

    private void editBgAmtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBgAmtBtnActionPerformed
        editBudgetDialog.pack();
        editBudgetDialog.setLocationRelativeTo(null);
        editBudgetDialog.setSize(new Dimension(590, 330));
        editBudgetDialog.setVisible(true);
    }//GEN-LAST:event_editBgAmtBtnActionPerformed

    private void editExpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpBtnActionPerformed
        editExpDialog.pack();
        editExpDialog.setLocationRelativeTo(null);
        editExpDialog.setSize(new Dimension(690, 690));
        editExpDialog.setVisible(true);
    }//GEN-LAST:event_editExpBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        resetConfirmDialog.pack();
        resetConfirmDialog.setLocationRelativeTo(null);
        resetConfirmDialog.setSize(new Dimension(500, 300));
        resetConfirmDialog.setVisible(true);
    }//GEN-LAST:event_resetBtnActionPerformed


    private void editExpTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editExpTableMouseClicked
        msgLabelEditExp.setText("");
        DefaultTableModel expTableModel = (DefaultTableModel) editExpTable.getModel();
        editExpPurposeInput.setText(expTableModel.getValueAt(editExpTable.getSelectedRow(), 0).toString());
        editExpAmtInput.setText(expTableModel.getValueAt(editExpTable.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_editExpTableMouseClicked

    private void editExpUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpUpdateBtnActionPerformed
        DefaultTableModel editExpTableModel = (DefaultTableModel) editExpTable.getModel();
        DefaultTableModel expTableModel = (DefaultTableModel) expTable.getModel();
        int selectedRow = editExpTable.getSelectedRow();
        try{
            if(selectedRow == -1){
                msgLabelEditExp.setText("No selected item. Please select the item you want by clicking its row.");
                msgLabelEditExp.setForeground(Color.red);
            }else{
                if(editExpPurposeInput.getText().trim().equals("")){
                    msgLabelEditExp.setText("Expense purpose cannot be blank.");
                    msgLabelEditExp.setForeground(Color.red);
                }else{
                    msgLabelEditExp.setText("");
                    //update expense info
                    Expense selectedExpense = budgetList.getBudgetItem(budgetIndex).getExpenseItem(selectedRow);
                    selectedExpense.setExpensePurpose(editExpPurposeInput.getText());
                    selectedExpense.setExpenseAmount(Integer.parseInt(editExpAmtInput.getText()));
                    editExpTableModel.setValueAt(editExpPurposeInput.getText(), selectedRow, 0);
                    editExpTableModel.setValueAt(editExpAmtInput.getText(), selectedRow, 1);

                    //update total expense and total balance
                    expTableModel.setValueAt(editExpPurposeInput.getText(), selectedRow, 0);
                    expTableModel.setValueAt(editExpAmtInput.getText(), selectedRow, 1);
                    totalExpContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getTotalExpense()));
                    balanceContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBalance()));
                }
            }
        }catch(NumberFormatException nfe){
            msgLabelEditExp.setText("Budget amount is not an integer. Please re-enter.");
            msgLabelEditExp.setForeground(Color.red);
        }catch (ExpensePurposeHasCommaException expenseCommaException){
            msgLabelEditExp.setText(expenseCommaException.purposeCommaMsg());
            msgLabelEditExp.setForeground(Color.red);
        }
    }//GEN-LAST:event_editExpUpdateBtnActionPerformed

    private void editExpInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpInsertBtnActionPerformed
        DefaultTableModel editExpTableModel = (DefaultTableModel) editExpTable.getModel();
        DefaultTableModel expTableModel = (DefaultTableModel) expTable.getModel();
        try{
            if(editExpPurposeInput.getText().trim().equals("")){
                msgLabelEditExp.setText("Expense purpose cannot be blank.");
                msgLabelEditExp.setForeground(Color.red);
            }else{
                msgLabelEditExp.setText("");
                Expense expense = new Expense(editExpPurposeInput.getText(),Integer.parseInt(editExpAmtInput.getText()));
                editExpTableModel.addRow(new Object[]{editExpPurposeInput.getText(),editExpAmtInput.getText()});
                budgetList.getBudgetItem(budgetIndex).addExpense(expense);

                //update total expense and total balance
                expTableModel.addRow(new Object[]{editExpPurposeInput.getText(),editExpAmtInput.getText()});
                totalExpContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getTotalExpense()));
                balanceContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBalance()));
            }
        }catch(NumberFormatException nfe){
            msgLabelEditExp.setText("Budget amount is not an integer. Please re-enter.");
            msgLabelEditExp.setForeground(Color.red);
        }catch (ExpensePurposeHasCommaException expenseCommaException){
            msgLabelEditExp.setText(expenseCommaException.purposeCommaMsg());
            msgLabelEditExp.setForeground(Color.red);
        }
    }//GEN-LAST:event_editExpInsertBtnActionPerformed

    private void editExpRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpRemoveBtnActionPerformed
        int selectedRow = editExpTable.getSelectedRow();
        if(selectedRow == -1){
            msgLabelEditExp.setText("No selected item. Please select the item you want by clicking its row.");
            msgLabelEditExp.setForeground(Color.red);
        }else{
            removeExpDialog.pack();
            removeExpDialog.setLocationRelativeTo(null);
            removeExpDialog.setSize(new Dimension(500, 300));
            removeExpDialog.setVisible(true);
        }
    }//GEN-LAST:event_editExpRemoveBtnActionPerformed

    private void editExpFinishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpFinishBtnActionPerformed
        editExpPurposeInput.setText("");
        msgLabelEditExp.setText("");
        editExpDialog.dispose();
    }//GEN-LAST:event_editExpFinishBtnActionPerformed

    private void confirmRemoveExpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRemoveExpBtnActionPerformed
        DefaultTableModel editExpTableModel = (DefaultTableModel) editExpTable.getModel();
        DefaultTableModel expTableModel = (DefaultTableModel) expTable.getModel();
        int selectedRow = editExpTable.getSelectedRow();
        Expense selectedExpense = budgetList.getBudgetItem(budgetIndex).getExpenseItem(selectedRow);
        budgetList.getBudgetItem(budgetIndex).removeExpense(selectedExpense);
        editExpTableModel.removeRow(selectedRow);
        editExpPurposeInput.setText("");
        editExpAmtInput.setText("");

        //update total expense and total balance
        expTableModel.removeRow(selectedRow);
        totalExpContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getTotalExpense()));
        balanceContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBalance()));

        removeExpDialog.dispose();
        msgLabelEditExp.setText("The selected expense has been removed.");
    }//GEN-LAST:event_confirmRemoveExpBtnActionPerformed

    private void cancelRemoveExpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRemoveExpBtnActionPerformed
        removeExpDialog.dispose();
    }//GEN-LAST:event_cancelRemoveExpBtnActionPerformed



    private void submitEditTitleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditTitleBtnActionPerformed
        try{
            if(newTitleInput.getText().trim().isEmpty()){
                msgLabelEditTitle.setText("New title cannot be left blank.");
                msgLabelEditTitle.setForeground(Color.red);
            }else{
                budgetList.getBudgetItem(budgetIndex).setTitle(newTitleInput.getText());
                bgTitleContent.setText(budgetList.getBudgetItem(budgetIndex).getTitle());
                editTitleDialog.dispose();
                newTitleInput.setText("");
                msgLabelEditExp.setText("");
            }
        }catch(TitleHasCommaException titleCommaException){
            msgLabelEditTitle.setText(titleCommaException.titleHasCommaMsg());
            msgLabelEditTitle.setForeground(Color.red);
        }
    }//GEN-LAST:event_submitEditTitleBtnActionPerformed

    private void cancelEditTitleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditTitleBtnActionPerformed
        newTitleInput.setText("");
        msgLabelEditExp.setText("");
        editTitleDialog.dispose();
    }//GEN-LAST:event_cancelEditTitleBtnActionPerformed

    
    
    private void submitEditBgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditBgBtnActionPerformed
        try{
            budgetList.getBudgetItem(budgetIndex).setBudget(Integer.parseInt(newAmtInput.getText()));
            bgAmtContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBudget()));
            balanceContent.setText(Integer.toString(budgetList.getBudgetItem(budgetIndex).getBalance()));
            editBudgetDialog.dispose();
            newAmtInput.setText("");
            msgLabelEditExp.setText("");
        }catch(NumberFormatException numberFormatException){
            msgLabelEditBg.setText("Budget amount is not an integer or left blank. Please re-enter.");
            msgLabelEditBg.setForeground(Color.red);
        }
    }//GEN-LAST:event_submitEditBgBtnActionPerformed

    private void cancelEditBgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditBgBtnActionPerformed
        newAmtInput.setText("");
        msgLabelEditExp.setText("");
        editBudgetDialog.dispose();
    }//GEN-LAST:event_cancelEditBgBtnActionPerformed


    private void confirmResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmResetBtnActionPerformed
        budgetList.getBudgetItem(budgetIndex).clearBudget();
        resetConfirmDialog.dispose();
        displayResetData();
        msgLabel.setText("Budget and expense amounts have been reset.");
        msgLabelEditBg.setForeground(Color.blue);
    }//GEN-LAST:event_confirmResetBtnActionPerformed

    private void cancelResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResetBtnActionPerformed
        resetConfirmDialog.dispose();
    }//GEN-LAST:event_cancelResetBtnActionPerformed

    private void menuSaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSaveBtnMouseClicked
        this.dispose();
        GUISaveToTextFile saveToTextFile = new GUISaveToTextFile(budgetList);
        saveToTextFile.setVisible(true);
    }//GEN-LAST:event_menuSaveBtnMouseClicked

    private void menuDownloadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDownloadBtnMouseClicked
        this.dispose();
        GUIDownloadTextFile downloadTextFile = new GUIDownloadTextFile(budgetList);
        downloadTextFile.setVisible(true);
    }//GEN-LAST:event_menuDownloadBtnMouseClicked

    private void menuLoadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLoadBtnMouseClicked
        this.dispose();
        GUILoadTextFile loadTextFile = new GUILoadTextFile(budgetList);
        loadTextFile.setVisible(true);
    }//GEN-LAST:event_menuLoadBtnMouseClicked

    private void menuViewBgListBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuViewBgListBtnMouseClicked
        this.dispose();
        GUIViewBudgetList viewBudgetList = new GUIViewBudgetList(budgetList);
        viewBudgetList.setVisible(true);
    }//GEN-LAST:event_menuViewBgListBtnMouseClicked

    //Menu bar
    private void menuCreateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCreateBtnMouseClicked
        this.dispose();
        GUICreateBudget createBudget = new GUICreateBudget(budgetList);
        createBudget.setVisible(true);
    }//GEN-LAST:event_menuCreateBtnMouseClicked






    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIViewBudgetDetail(new BudgetList(),0).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtCAD;
    private javax.swing.JLabel askResetConfirmation;
    private javax.swing.JLabel balanceContent;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel bgAmtContent;
    private javax.swing.JLabel bgAmtLabel;
    private javax.swing.JLabel bgTitleContent;
    private javax.swing.JLabel bgTitleLabel;
    private javax.swing.JButton cancelEditBgBtn;
    private javax.swing.JButton cancelEditTitleBtn;
    private javax.swing.JButton cancelRemoveExpBtn;
    private javax.swing.JButton cancelResetBtn;
    private javax.swing.JButton confirmRemoveExpBtn;
    private javax.swing.JButton confirmResetBtn;
    private javax.swing.JButton editBgAmtBtn;
    private javax.swing.JPanel editBgAmtPanel;
    private javax.swing.JButton editBgTitleBtn;
    private javax.swing.JDialog editBudgetDialog;
    private javax.swing.JTextField editExpAmtInput;
    private javax.swing.JLabel editExpAmtLabel;
    private javax.swing.JButton editExpBtn;
    private javax.swing.JLabel editExpClickRowMsg;
    private javax.swing.JDialog editExpDialog;
    private javax.swing.JButton editExpFinishBtn;
    private javax.swing.JButton editExpInsertBtn;
    private javax.swing.JPanel editExpPanel;
    private javax.swing.JTextField editExpPurposeInput;
    private javax.swing.JLabel editExpPurposeLabel;
    private javax.swing.JButton editExpRemoveBtn;
    private javax.swing.JTable editExpTable;
    private javax.swing.JScrollPane editExpTablePanel;
    private javax.swing.JButton editExpUpdateBtn;
    private javax.swing.JDialog editTitleDialog;
    private javax.swing.JLabel enterAmtLabel;
    private javax.swing.JLabel enterTitleLabel;
    private javax.swing.JLabel expLabel;
    private javax.swing.JTable expTable;
    private javax.swing.JScrollPane expTablePanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCreateBtn;
    private javax.swing.JMenu menuDownloadBtn;
    private javax.swing.JMenu menuLoadBtn;
    private javax.swing.JMenu menuSaveBtn;
    private javax.swing.JMenu menuViewBgListBtn;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel msgLabelEditBg;
    private javax.swing.JLabel msgLabelEditExp;
    private javax.swing.JLabel msgLabelEditTitle;
    private javax.swing.JLabel msgLabelRemoveExp;
    private javax.swing.JLabel msgLabelReset;
    private javax.swing.JTextField newAmtInput;
    private javax.swing.JTextField newTitleInput;
    private javax.swing.JPanel removeExpConfirmPanel;
    private javax.swing.JLabel removeExpConfirmation;
    private javax.swing.JDialog removeExpDialog;
    private javax.swing.JLabel requiredField;
    private javax.swing.JLabel requiredField1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JDialog resetConfirmDialog;
    private javax.swing.JPanel resetConfirmPanel;
    private javax.swing.JSeparator separatorLine;
    private javax.swing.JButton submitEditBgBtn;
    private javax.swing.JButton submitEditTitleBtn;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalExpContent;
    private javax.swing.JLabel totalExpLabel;
    private javax.swing.JPanel updateTitlePanel;
    private javax.swing.JLabel warningMsgRemoveExp;
    private javax.swing.JLabel warningMsgReset;
    // End of variables declaration//GEN-END:variables
}
