/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package track.it.gui;

import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import model.BudgetList;

/**
 *
 * @author kungcheow
 */
public class GUIViewBudgetList extends javax.swing.JFrame {
    private BudgetList budgetList;

    /**
     * Creates new form ViewBudgetList
     */
    public GUIViewBudgetList(BudgetList budgetList) {
        initComponents();
        this.budgetList = budgetList;
        if(budgetList.getBudgetListSize() == 0){
            msgLabel.setText("No budget in the record.");
        }else{
            addDataToExpenseTable(budgetListTable);
        }

    }

    private void addDataToExpenseTable(JTable jTable){
        DefaultTableModel bgTableModel = (DefaultTableModel) jTable.getModel();
        Object rowData[] = new Object[3];
        for(int i = 0; i < budgetList.getBudgetListSize();i++){
            rowData[0] = budgetList.getBudgetItem(i).getTitle();
            rowData[1] = budgetList.getBudgetItem(i).getBudget();
            rowData[2] = budgetList.getBudgetItem(i).getBalance();
            bgTableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeBgConfirmDialog = new javax.swing.JDialog();
        askRemoveConfirmPanel = new javax.swing.JPanel();
        askRemoveConfirmation = new javax.swing.JLabel();
        warningMsgRemoveBg = new javax.swing.JLabel();
        removeBgConfirmBtn = new javax.swing.JButton();
        cancelRemoveBgBtn = new javax.swing.JButton();
        viewBgListPanel = new javax.swing.JPanel();
        clickRowMsg = new javax.swing.JLabel();
        budgeListTablePanel = new javax.swing.JScrollPane();
        budgetListTable = new javax.swing.JTable();
        editBudgetBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        menuCreateBtn = new javax.swing.JMenu();
        menuViewBgListBtn = new javax.swing.JMenu();
        menuLoadBtn = new javax.swing.JMenu();
        menuDownloadBtn = new javax.swing.JMenu();
        menuSaveBtn = new javax.swing.JMenu();

        removeBgConfirmDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        removeBgConfirmDialog.setBackground(new java.awt.Color(255, 255, 255));

        askRemoveConfirmPanel.setBackground(new java.awt.Color(255, 255, 255));
        askRemoveConfirmPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));

        askRemoveConfirmation.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        askRemoveConfirmation.setForeground(new java.awt.Color(0, 51, 102));
        askRemoveConfirmation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        askRemoveConfirmation.setText("Do you want to remove the selected budget?");

        warningMsgRemoveBg.setForeground(new java.awt.Color(204, 0, 51));
        warningMsgRemoveBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningMsgRemoveBg.setText("Warning: This action cannot be undone.");

        removeBgConfirmBtn.setBackground(new java.awt.Color(0, 153, 153));
        removeBgConfirmBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        removeBgConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBgConfirmBtn.setText("Yes");
        removeBgConfirmBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        removeBgConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBgConfirmBtnActionPerformed(evt);
            }
        });

        cancelRemoveBgBtn.setBackground(new java.awt.Color(0, 51, 102));
        cancelRemoveBgBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        cancelRemoveBgBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelRemoveBgBtn.setText("No");
        cancelRemoveBgBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelRemoveBgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRemoveBgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout askRemoveConfirmPanelLayout = new javax.swing.GroupLayout(askRemoveConfirmPanel);
        askRemoveConfirmPanel.setLayout(askRemoveConfirmPanelLayout);
        askRemoveConfirmPanelLayout.setHorizontalGroup(
            askRemoveConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, askRemoveConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(askRemoveConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(askRemoveConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(askRemoveConfirmation)
                        .addGroup(askRemoveConfirmPanelLayout.createSequentialGroup()
                            .addComponent(removeBgConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cancelRemoveBgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addGroup(askRemoveConfirmPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(warningMsgRemoveBg)))
                .addGap(74, 74, 74))
        );
        askRemoveConfirmPanelLayout.setVerticalGroup(
            askRemoveConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(askRemoveConfirmPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(askRemoveConfirmation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningMsgRemoveBg)
                .addGap(24, 24, 24)
                .addGroup(askRemoveConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBgConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelRemoveBgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout removeBgConfirmDialogLayout = new javax.swing.GroupLayout(removeBgConfirmDialog.getContentPane());
        removeBgConfirmDialog.getContentPane().setLayout(removeBgConfirmDialogLayout);
        removeBgConfirmDialogLayout.setHorizontalGroup(
            removeBgConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(askRemoveConfirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        removeBgConfirmDialogLayout.setVerticalGroup(
            removeBgConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(askRemoveConfirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget List");
        setBackground(new java.awt.Color(255, 255, 255));

        viewBgListPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewBgListPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4));

        clickRowMsg.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        clickRowMsg.setText("Click row to select budget");

        budgetListTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        budgetListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Budget amount (CAD)", "Balance (CAD)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        budgeListTablePanel.setViewportView(budgetListTable);

        editBudgetBtn.setBackground(new java.awt.Color(0, 153, 153));
        editBudgetBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editBudgetBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBudgetBtn.setText("View/edit selected budget");
        editBudgetBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editBudgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBudgetBtnActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(102, 102, 102));
        removeBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setText("Remove selected budget");
        removeBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        msgLabel.setForeground(new java.awt.Color(0, 153, 153));
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout viewBgListPanelLayout = new javax.swing.GroupLayout(viewBgListPanel);
        viewBgListPanel.setLayout(viewBgListPanelLayout);
        viewBgListPanelLayout.setHorizontalGroup(
            viewBgListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBgListPanelLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(viewBgListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clickRowMsg)
                    .addComponent(budgeListTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewBgListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(msgLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(viewBgListPanelLayout.createSequentialGroup()
                            .addComponent(editBudgetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(82, 82, 82))
        );
        viewBgListPanelLayout.setVerticalGroup(
            viewBgListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBgListPanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(budgeListTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clickRowMsg)
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(viewBgListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(editBudgetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));

        menuCreateBtn.setText("Create budget");
        menuCreateBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuCreateBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuCreateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCreateBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuCreateBtn);

        menuViewBgListBtn.setForeground(new java.awt.Color(0, 51, 102));
        menuViewBgListBtn.setText("View budgets");
        menuViewBgListBtn.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        menuViewBgListBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuBar.add(menuViewBgListBtn);

        menuLoadBtn.setText("Load");
        menuLoadBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuLoadBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuLoadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLoadBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuLoadBtn);

        menuDownloadBtn.setText("Download");
        menuDownloadBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuDownloadBtn.setMargin(new java.awt.Insets(0, 0, 0, 10));
        menuDownloadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDownloadBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuDownloadBtn);

        menuSaveBtn.setText("Save");
        menuSaveBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        menuSaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSaveBtnMouseClicked(evt);
            }
        });
        menuBar.add(menuSaveBtn);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewBgListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewBgListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(666, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void editBudgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBudgetBtnActionPerformed
        int selectedBgIndex = budgetListTable.getSelectedRow();
        if(selectedBgIndex == -1){
            msgLabel.setText("No selected item. Please select the item you want by clicking its row.");
            msgLabel.setForeground(Color.red);
        }

        else {
            GUIViewBudgetDetail guiViewBudgetDetail = new GUIViewBudgetDetail(budgetList, selectedBgIndex);
            guiViewBudgetDetail.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_editBudgetBtnActionPerformed


    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int selectedBgIndex = budgetListTable.getSelectedRow();
        if(selectedBgIndex == -1){
            msgLabel.setText("No selected item. Please select the item you want by clicking its row.");
            msgLabel.setForeground(Color.red);
        }else{
            removeBgConfirmDialog.pack();
            removeBgConfirmDialog.setLocationRelativeTo(null);
            removeBgConfirmDialog.setSize(new Dimension(520, 270));
            removeBgConfirmDialog.setVisible(true);
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void removeBgConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBgConfirmBtnActionPerformed
        DefaultTableModel bgTableModel = (DefaultTableModel) budgetListTable.getModel();
        int selectedBgIndex = budgetListTable.getSelectedRow();
        budgetList.removeBudget(selectedBgIndex);
        bgTableModel.removeRow(selectedBgIndex);
        removeBgConfirmDialog.dispose();
        msgLabel.setText("The budget has been removed.");
        msgLabel.setForeground(Color.blue);

    }//GEN-LAST:event_removeBgConfirmBtnActionPerformed

    private void cancelRemoveBgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRemoveBgBtnActionPerformed
        removeBgConfirmDialog.dispose();
    }//GEN-LAST:event_cancelRemoveBgBtnActionPerformed

    private void menuCreateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCreateBtnMouseClicked
        this.dispose();
        GUICreateBudget createBudget = new GUICreateBudget(budgetList);
        createBudget.setVisible(true);
    }//GEN-LAST:event_menuCreateBtnMouseClicked

    private void menuLoadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLoadBtnMouseClicked
        this.dispose();
        GUILoadTextFile loadTextFile = new GUILoadTextFile(budgetList);
        loadTextFile.setVisible(true);
    }//GEN-LAST:event_menuLoadBtnMouseClicked

    private void menuDownloadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDownloadBtnMouseClicked
        this.dispose();
        GUIDownloadTextFile downloadTextFile = new GUIDownloadTextFile(budgetList);
        downloadTextFile.setVisible(true);
    }//GEN-LAST:event_menuDownloadBtnMouseClicked

    private void menuSaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSaveBtnMouseClicked
        this.dispose();
        GUISaveToTextFile saveToTextFile = new GUISaveToTextFile(budgetList);
        saveToTextFile.setVisible(true);
    }//GEN-LAST:event_menuSaveBtnMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIViewBudgetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIViewBudgetList(new BudgetList()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel askRemoveConfirmPanel;
    private javax.swing.JLabel askRemoveConfirmation;
    private javax.swing.JScrollPane budgeListTablePanel;
    private javax.swing.JTable budgetListTable;
    private javax.swing.JButton cancelRemoveBgBtn;
    private javax.swing.JLabel clickRowMsg;
    private javax.swing.JButton editBudgetBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCreateBtn;
    private javax.swing.JMenu menuDownloadBtn;
    private javax.swing.JMenu menuLoadBtn;
    private javax.swing.JMenu menuSaveBtn;
    private javax.swing.JMenu menuViewBgListBtn;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton removeBgConfirmBtn;
    private javax.swing.JDialog removeBgConfirmDialog;
    private javax.swing.JButton removeBtn;
    private javax.swing.JPanel viewBgListPanel;
    private javax.swing.JLabel warningMsgRemoveBg;
    // End of variables declaration//GEN-END:variables
}
